In [2]:
notes =[12 , 16 , 89 , 23 , 40 , 50]

In [3]:
import numpy as np

In [4]:
notes_array = np.array(notes)

In [5]:
notes_array[2] = 20

In [6]:
notes_array

array([12, 16, 20, 23, 40, 50])

In [7]:
notes_array[2:]

array([20, 23, 40, 50])

In [8]:
notes_array[: :2]

array([12, 20, 40])

In [14]:
comp_array  = [ it for it in notes_array if it>= 15 ]

In [15]:
comp_array

[16, 20, 23, 40, 50]

In [37]:
notes_array[notes_array >= 15]

array([16, 20, 23, 40, 50])

In [38]:
x = [-2 , -1 , 1 , 2]

In [40]:
array_x = np.array(x)
array_x

array([-2, -1,  1,  2])

In [41]:
array_x.abs()

AttributeError: 'numpy.ndarray' object has no attribute 'abs'